name: HSI

#proxy:
#  host: yourproxy.local
#  port: 8080

HSI:
  authURL:
    int: https://authme-int.myhermes.de/authorization-facade/oauth2/access_token
    prod: https://authme.myhermes.de/authorization-facade/oauth2/access_token
  codeURL:
    int: https://authme-int.myhermes.de/authorization-facade/oauth2/authorize
    prod: https://authme.myhermes.de/authorization-facade/oauth2/authorize
  infoURL:
    int: https://authme-int.myhermes.de/authorization-facade/oauth2/tokeninfo
    prod: https://authme.myhermes.de/authorization-facade/oauth2/tokeninfo
  baseURL:
    int: https://de-api-int.hermesworld.com/esb-webservice-gateway/services/rest/1/sci
    prod: https://de-api.hermesworld.com/esb-webservice-gateway/services/rest/1/sci

  shipmentorderlistPath: /v1/shipmentorders
  shipmentorderPath: /v1/shipmentorders
  shipmentorderlabelPath: /v1/shipmentorders/:shipmentOrderID:/labels
  shipmentlabelPath: /v1/shipmentorders/labels
  shipmentstatusPath: /v1/shipmentstatuses/current
  shipmenthistoryPath: /v1/shipmentstatuses

  returnorder_v1Path: /v1/returnorders
  returnorderlabel_v1Path: /v1/returnorders/:returnOrderID:/labels

  returnorder_v2Path: /v2/returnorders
  returnlabel_v2Path: /v2/returnorders/labels
  returnorderlabel_v2Path: /v2/returnorders/:returnOrderID:/labels

  returnpickuporderPath: /v1/returnpickuporders
